---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.4
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[gitweb]
    attributes:
      gitweb:
        server:
          name: 'git.mydomain.com'
